name = "hugo-theme-light"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "hugo-theme-light is blog theme for hugo."
tags = ["blog"]
features = ["blog"]
min_version = 0.15

[author]
    name = "Lencerf"
    homepage = "http://lencerf.github.io/"

